title: Jennifer Ma # your name (or website title) here
logo: "/images/Jennifer_Ma_Headshot.png?raw=true"
description: |
  As an aspiring data scientist, I am deeply passionate about utilizing the power of data to drive positive change and make a meaningful impact. My passion lies in how we can leverage data to solve complex problems for social good.
theme: jekyll-theme-minimal
