title: Jennifer Ma # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello and welcome to my portfolio page! My name is [Your Name], and I am an aspiring data scientist with a strong interest in health care. I am passionate about using data to improve health outcomes and am constantly seeking ways to apply my skills to this field.
  <br><br>
  I am excited about the potential for data science to transform health care and improve patient outcomes. I believe that my skills and passion for this field make me a strong candidate for roles that involve data analysis and modeling in health care.
  <br><br>
  Thank you for taking the time to visit my portfolio page. Please feel free to explore my work and contact me if you have any questions or would like to discuss potential opportunities.
  <br><br>
  <a href="https://www.linkedin.com/in/jennifer-ma-951883164/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

